name: Backend CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Download dependencies
        working-directory: backend
        run: go mod download

      - name: Run tests
        working-directory: backend
        run: go test -v ./...

  lint:
    name: Lint, Format & Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Check formatting
        working-directory: backend
        run: |
          UNFORMATTED=$(go fmt ./...)
          if [ -n "$UNFORMATTED" ]; then
            echo "These files need formatting:"
            echo "$UNFORMATTED"
            exit 1
          fi

      - name: Run go vet
        working-directory: backend
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: backend
        run: ~/go/bin/staticcheck ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        working-directory: backend
        run: ~/go/bin/gosec ./...
