name: Frontend CI
on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: frontend/*


      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Run ESLint
        working-directory: frontend
        run: pnpm run lint

      - name: Build project
        working-directory: frontend
        run: pnpm run build

      - name: Run tests
        working-directory: frontend
        run: pnpm run test
